x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: Dockerfile

  env_file:
    - .env

  environment:
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor

    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${AIRFLOW_DB}

    AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${AIRFLOW_DB}

    AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0

    AIRFLOW__CORE__FERNET_KEY: ${FERNET_KEY}

    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"

    AIRFLOW__CORE__LOAD_EXAMPLES: "false"

    AIRFLOW__API__AUTH_BACKENDS: airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session

    AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: "true"

 
  volumes:
    - ./dags:/opt/airflow/dags
    - ./data:/opt/airflow/data
    - ./src:/opt/airflow/src
    - airflow-logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins

    # volumes:
    # - ./dags:/opt/airflow/dags
    # - ./src:/opt/airflow/src
    # - ./data:/opt/airflow/data

  depends_on:
    postgres:
      condition: service_healthy

    redis:
      condition: service_healthy

services:

  postgres:
    image: postgres:16
    container_name: youtube-postgres

    env_file:
      - .env

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${AIRFLOW_DB}

    ports:
      - "5432:5432"

    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
      - ./docker/postgres/init-multiple-databases.sh:/docker-entrypoint-initdb.d/init-multiple-databases.sh

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${AIRFLOW_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

    restart: always


  redis:
    image: redis:7.2-bookworm
    container_name: youtube-redis

    expose:
      - "6379"

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

    restart: always


  airflow-init:
    <<: *airflow-common

    container_name: airflow-init

    entrypoint: /bin/bash

    command:
      - -c
      - |
        airflow db migrate &&
        airflow users create \
          --username ${AIRFLOW_ADMIN_USERNAME} \
          --password ${AIRFLOW_ADMIN_PASSWORD} \
          --firstname Admin \
          --lastname User \
          --role Admin \
          --email admin@example.com || true

    user: "0:0"


  airflow-webserver:
    <<: *airflow-common

    container_name: airflow-webserver

    command: webserver

    ports:
      - "8080:8080"

    depends_on:
      postgres:
        condition: service_healthy

      redis:
        condition: service_healthy

      airflow-init:
        condition: service_completed_successfully

    restart: always


  airflow-scheduler:
    <<: *airflow-common

    container_name: airflow-scheduler

    command: scheduler

    depends_on:
      postgres:
        condition: service_healthy

      redis:
        condition: service_healthy

      airflow-init:
        condition: service_completed_successfully

    restart: always


  airflow-worker:
    <<: *airflow-common

    container_name: airflow-worker

    command: celery worker

    depends_on:
      postgres:
        condition: service_healthy

      redis:
        condition: service_healthy

      airflow-init:
        condition: service_completed_successfully

    restart: always


volumes:
  postgres-db-volume:
  airflow-logs: